AWSTemplateFormatVersion: '2010-09-09'
Description: 'This template creates an Amazon Relational Database Service database instance.'
Parameters:
  DBClass:
    AllowedValues:
    - db.t2.medium
    - db.t2.large
    Type: String
  DBAllocatedStorage:
    ConstraintDescription: must be between 5 and 1024Gb.
    Default: '100'
    Description: The size of the database (Gb)
    MaxValue: '1024'
    MinValue: '5'
    Type: Number
  DBSubnetGroup0:
    Description: The SubnetIds for the DB to be deployed
    Type: AWS::EC2::Subnet::Id
  DBSubnetGroup1:
    Description: The SubnetIds for the DB to be deployed
    Type: AWS::EC2::Subnet::Id
  DBInstance:
    Description: The DB instance identifier
    Type: String
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: must begin with a letter and contain only alphanumeric
      characters.
  MultiAZDatabase:
    AllowedValues:
    - 'true'
    - 'false'
    Default: 'true'
    Description: Create a Multi-AZ MySQL Amazon RDS database instance
    Type: String
  DBSecurityGroup:
    Description: The Security group List
    Type: AWS::EC2::SecurityGroup::Id
  DBName:
    Default: demoaudit
    Description: The database name
    Type: String
    MinLength: '1'
    MaxLength: '64'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: must begin with a letter and contain only alphanumeric
      characters.
  DBUser:
    NoEcho: 'false'
    Description: The database admin account username
    Type: String
    MinLength: '1'
    MaxLength: '16'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: must begin with a letter and contain only alphanumeric
      characters.
  DBPassword:
    NoEcho: 'true'
    Description: The database admin account password
    Type: String
    MinLength: '8'
    MaxLength: '41'
    AllowedPattern: '[a-zA-Z0-9]*'
    ConstraintDescription: must contain only alphanumeric characters.
Resources:
  MyDB:
    Type: AWS::RDS::DBInstance
    Properties:
      DBName: !Ref 'DBName'
      AllocatedStorage: !Ref 'DBAllocatedStorage'
      DBInstanceClass: !Ref 'DBClass'
      DBInstanceIdentifier: !Ref DBInstance
      AllowMajorVersionUpgrade: false
      AutoMinorVersionUpgrade: true
      BackupRetentionPeriod: 30
      PubliclyAccessible: false
      Engine: MySQL
      EngineVersion: 5.7.16
      MasterUsername: !Ref 'DBUser'
      MasterUserPassword: !Ref 'DBPassword'
      DBParameterGroupName: !Ref 'MyRDSParamGroup'
      DBSubnetGroupName: !Ref 'MySQLSubnetGroup'
      MultiAZ: !Ref MultiAZDatabase
      VPCSecurityGroups:
        - !Ref 'DBSecurityGroup'
    DeletionPolicy: Snapshot
  MySQLSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: DB Subnet Groups
      SubnetIds:
        - !Ref DBSubnetGroup0
        - !Ref DBSubnetGroup1
  MyRDSParamGroup:
    Type: AWS::RDS::DBParameterGroup
    Properties:
      Family: MySQL5.7
      Description: CloudFormation Database Parameter Group
Outputs:
  JDBCConnectionString:
    Description: JDBC connection string for the database
    Value: !Join ['', ['jdbc:mysql://', !GetAtt [MyDB, Endpoint.Address], ':', !GetAtt [
          MyDB, Endpoint.Port], /, !Ref 'DBName']]
